### ISSUE TITLE
Milestone items

### ISSUE THREAD

**Issue by Kristories** [tenancy/hyn-nova#1]
Do you have milestone here? Maybe we can help to develop this nova package.

Thanks.

**Comment by luceos** [comment]
The prime blocker right now is the ability to switch between tenant. I'm pretty caught up in other (non-foss) work so I can't push this package to completion very soon.

Feel free to PR functionality that adds the switcher and/or do a test run with the current source to see if anything is missing 👍 

With enough confirmation I might be tagging a first version..

**Comment by Plytas** [comment]
What was your idea behind switching tenants?

**Comment by luceos** [comment]
Aside from being able to manage the system models it would be great being able to manage the tenant models. In order to do so:

- Nova should only show/configure the tenant models when a tenant is identified/forced or we need to pick a random first..
- Nova should allow switching Tenant using the Environment `tenant($website)` method. This might be a little bit more complicated as Nova is a SPA... Otherwise we should be able to rely on hostname based auto switching.

I haven't looked into this, but it would be pretty awesome if this could be achieved.
